import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    zIndex: 2,
    marginTop: 35,
  },
  perfil: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    top: 10,
    zIndex: 2,
  },
  perfilImagem: {
    width: 40,
    height: 40,
    borderRadius: 50,
    // borderColor: "#aa00a9",
    // borderWidth: 1,
    borderWidth: 1,
    borderColor: "#000",
    boxShadow: "1px 1px 1px 1px #aa00a9",
    zIndex: 2,
  },
  perfilNome: {
    color: "#fff",
    fontSize: 18,
    marginLeft: 10,
    fontWeight: "bold",
    zIndex: 2,
  },
  recomendados: {
    color: "#fff",
    fontSize: 25,
    marginBottom: 20,
    marginTop: 20,
    fontWeight: "bold",
    alignSelf: "center",
    marginVertical: 10,
    zIndex: 2,
  },
  cardsArtistas: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    zIndex: 2,
  },
  cardBoxArtistas: {
    borderWidth: 1,
    borderColor: "#000",
    boxShadow: "1px 1px 1px 1px #aa00a9",
    margin: 5,
    borderRadius: 30,
    zIndex: 2,
  },
  cardsMusicas: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    zIndex: 2,
  },
  cardBoxMusicas: {
    width: 180,
    height: 90,
    borderWidth: 1,
    borderColor: "#000",
    boxShadow: "1px 1px 1px 1px #aa00a9",
    margin: 5,
    borderRadius: 10,
    zIndex: 2,
  },
  cardImgMusicas: {
    width: 180,
    height: 50,
    borderRadius: 10,
    borderColor: "#2e2e2eff",
    borderWidth: 1,
    zIndex: 2,
  },
  cardBoxAlbuns: {
    width: 400,
    height: 100,
    borderWidth: 1,
    borderColor: "#000",
    boxShadow: "1px 1px 1px 1px #aa00a9",
    margin: 5,
    borderRadius: 100,
    zIndex: 2,
  },
  cardsAlbuns: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    zIndex: 2,
    marginBottom: 20,
  },
  cardImgAlbuns: {
    width: 100,
    height: 100,
    borderRadius: 100,
    borderColor: "#2e2e2eff",
    borderWidth: 1,
    zIndex: 2,
  },
  cardImg: {
    width: 110,
    height: 110,
    borderRadius: 30,
    borderColor: "#2e2e2eff",
    borderWidth: 1,
    zIndex: 2,
  },
  gradient: {
    position: "absolute",
    top: 0,
    right: 0,
    width: "150%",
    height: "150%",
  },
});
